toc-title-document: "Innholdsfortegnelse"
toc-title-website: "På denne siden"

related-formats-title: "Andre formater"
related-notebooks-title: "Notebooks"
source-notebooks-prefix: "Kildekode"

section-title-abstract: "Sammendrag"
section-title-appendices: "Vedlegg"
section-title-footnotes: "Fotnoter"
section-title-references: "Kilder"
section-title-reuse: "Gjenbruk"
section-title-copyright: "Opphavsrett"
section-title-citation: "Sitat"

appendix-attribution-cite-as: "For attribusjon, siter dette verket som:"
appendix-attribution-bibtex: "BibTeX sitat:"

title-block-author-single: "Av"
title-block-author-plural: "Av"
title-block-affiliation-single: "Tilknytning"
title-block-affiliation-plural: "Tilknytninger"
title-block-published: "Publisert"
title-block-modified: "Modifisert"

callout-tip-title: "Tips"
callout-note-title: "Merk"
callout-warning-title: "Advarsel"
callout-important-title: "Viktig"
callout-caution-title: "Fare"

code-summary: "Kode"

code-tools-menu-caption: "Kode"
code-tools-show-all-code: "Vis all kode"
code-tools-hide-all-code: "Skjul all kode"
code-tools-view-source: "Se kildekode"
code-tools-source-code: "Kildekode"

code-line: "Linje"
code-lines: "Linjer"

copy-button-tooltip: "Kopier til utklippstavle"
copy-button-tooltip-success: "Kopiert!"

repo-action-links-edit: "Rediger denne siden"
repo-action-links-source: "Se kildekode"
repo-action-links-issue: "Rapporter en feil"

back-to-top: "Til toppen"

search-no-results-text: "Ingen resultater"
search-matching-documents-text: "treff"
search-copy-link-title: "Kopier lenke til søk"
search-hide-matches-text: "Skjul andre treff"
search-more-match-text: "flere treff i dokumentet"
search-more-matches-text: "flere treff i dokumentet"
search-clear-button-title: "Fjern"
search-detached-cancel-button-title: "Avbryt"
search-submit-button-title: "Send inn"
search: "Søk"

toggle-section: "Veksle avsnitt"
toggle-sidebar: "Veksle sidemenynavigering"
toggle-dark-mode: "Veksle mørkeleggingsmodus"
toggle-reader-mode: "Veksle lesemodus "
toggle-navigation: "Veksle navigasjon"

crossref-fig-title: "Figur"
crossref-tbl-title: "Tabell"
crossref-lst-title: "Liste"
crossref-thm-title: "Teori"
crossref-lem-title: "Lemma"
crossref-cor-title: "Følgesats"
crossref-prp-title: "Påstand"
crossref-cnj-title: "Formodning"
crossref-def-title: "Definisjon"
crossref-exm-title: "Eksempel"
crossref-exr-title: "Øvelse"
crossref-ch-prefix: "Kapittel"
crossref-apx-prefix: "Vedlegg"
crossref-sec-prefix: "Seksjon"
crossref-eq-prefix: "Formel"
crossref-lof-title: "Liste av figurer"
crossref-lot-title: "Liste av tabeller"
crossref-lol-title: "Liste av lister"

environment-proof-title: "Bevis"
environment-remark-title: "Anmerkning"
environment-solution-title: "Løsning"

listing-page-order-by: "Sortering"
listing-page-order-by-default: "Default"
listing-page-order-by-date-asc: "Eldst"
listing-page-order-by-date-desc: "Nyest"
listing-page-order-by-number-desc: "Høy til lav"
listing-page-order-by-number-asc: "Lav til høy"
listing-page-field-date: "Dato"
listing-page-field-title: "Tittel"
listing-page-field-description: "Beskrivelse"
listing-page-field-author: "Av"
listing-page-field-filename: "Filnavn"
listing-page-field-filemodified: "Endret"
listing-page-field-subtitle: "Undertittel"
listing-page-field-readingtime: "Lesetid"
listing-page-field-categories: "Kategorier"
listing-page-minutes-compact: "{0} min"
listing-page-category-all: "Alle"
listing-page-no-matches: "Ingen treff"
